### ISSUE TITLE
Help with install

### ISSUE THREAD

**Issue by arnoac** [hedii/Codeigniter-Forum#4]
So I installed it, but is it possible to have codeigniter in the root and install the forum in for example localhost/community?

Because I don't want the forum to be the homepage, I know I can set hte homepage in routes but it's nicer if it just got installed in a different folder but keeping the codeigniter files inside the root folder.

**Comment by hedii** [comment]
You can install it in a subfolder (like /your_site_folder/community) and then go to http://your_site.tld/community/ to launch the installer (the base url for the forum app will be asked by the installer). But you will have a complete codeigniter application in your_site_folder/community and codeigniter files will not be shared across the 2 instances.
Check this page on the ci documentation: http://www.codeigniter.com/user_guide/general/managing_apps.html?#running-multiple-applications-with-one-codeigniter-installation
It may be what you want to do, but keep in mind that some files in the app folder are updated by the installer the installation process. I never tried that personally so i cannot give you advices to do that...

But you can also start with the forum app and then remove every references to the forum and write your own application (create a blog controller, etc...) and keep the login, logout, register, user profile, etc...
