### ISSUE TITLE
Security issue in forum & post create process

### ISSUE THREAD

**Issue by jmgraeffe** [hedii/Codeigniter-Forum#6]
By sending a POST request manually to the create_forum page, it is possible to create a forum without being logged in.
I just tried this one but I think it will work on creating a topic or a post, too.

Maybe you already know this problem and you would fix this in the final release, if so, sorry for this issue report, but people may ignore your warning and use it in production. So I think it would be better to have this fixed.

**Comment by hedii** [comment]
Hi, would you send a pull request to solve that? I haven't worked on this project since a long time and I am not using codeigniter anymore for my other projects.

**Comment by jmgraeffe** [comment]
Yeah, I will do it soon.

Therefore I want to ask you if I can work on it by forking it and improve it to my needs. Is it ok for you?
The license is permitting this already, but I wanted to ask you before I do this because you may have interest in further development by yourself.

**Comment by hedii** [comment]
No problem ! Do it :)

**Comment by kumang93** [comment]
verivication email not work, guys? i try that not work org no function create in user controller ?

Thanks.

**Comment by hedii** [comment]
@kumang93 please open your own issue. it is not related to this one.

**Comment by amritsparsha** [comment]
Which type of password choose in localhost phpmyadmin, while changing the userpassword from database, can you help me.
