### ISSUE TITLE
Non-english char supprot

### ISSUE THREAD

**Issue by terrylinooo** [hedii/Codeigniter-Forum#7]
While I was creating forum, I got those message:
The Forum Title field may only contain alpha-numeric characters and spaces.
The Description field may only contain alpha-numeric characters and spaces.

Looks like only support Englsih chars.

BTW, very good forum for creating my own forum, thank you very much!

**Comment by hedii** [comment]
Not english characters, but only alpha-numeric characters or spaces.

You can modify this line: https://github.com/hedii/Codeigniter-Forum/blob/master/application/controllers/Forum.php#L159

with the codeigniter validation rules of your choice: http://www.codeigniter.com/user_guide/libraries/form_validation.html#rule-reference

If you want to allow everything, just remove 'alpha_numeric_spaces'
