### ISSUE TITLE
Registration send confirmation email

### ISSUE THREAD

**Issue by helloworld415** [hedii/Codeigniter-Forum#8]
this is your code below, but everytime I register new account  I always got this error but the data is stored in the database

this is the error 

A PHP Error was encountered

Severity: Warning

Message: mail(): Failed to connect to mailserver at "localhost" port 25, verify your "SMTP" and "smtp_port" setting in php.ini or use ini_set()

Filename: libraries/Email.php

Line Number: 1812

Backtrace:

File: C:\xampp\htdocs\Login_System\application\models\User_model.php
Line: 314
Function: send

File: C:\xampp\htdocs\Login_System\application\models\User_model.php
Line: 45
Function: send_confirmation_email

File: C:\xampp\htdocs\Login_System\application\controllers\User.php
Line: 113
Function: create_user

File: C:\xampp\htdocs\Login_System\index.php
Line: 292
Function: require_once

this it your code in user model

private function send_confirmation_email($username, $email) {
		
		// load email library and url helper
		$this->load->library('email');
		$this->load->helper('url');
		
		// get the site email address
		$email_address = $this->config->item('site_email');
		
		// initialize the email configuration
		$this->email->initialize(array(
			'mailtype' => 'html',
			'charset'  => 'utf-8'
		));
		
		// get user registration date
		$registration_date = $this->db->select('created_at')->from('users')->where('username', $username)->get()->row('created_at');
		
		// create a user email hash with user email and user registration date
		$hash = sha1($email . $registration_date);
		
		// prepare the email
		$this->email->from($email_address, $email_address);
		$this->email->to($email);
		$this->email->subject('Please confirm your email to validate your new user account.');
		$message  = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head><body>';
		$message .= "Hi " . $username . ",<br><br>";
		$message .= "Please click the link below to confirm your account on " . base_url() . "<br><br>";
		$message .= "Click this link: <a href=\"" . base_url() . "user/email_validation/" . $username . "/" . $hash . "\">Confirm your email and validate your account</a>";
		$message .= "</body></html>";
		$this->email->message($message);
		
		// send the email and return status
		return $this->email->send();
		
	}

- 

- 

- 

- Please help me :( I like your work btw

**Comment by hedii** [comment]
You have to be able to send php email on your machine with the php mail() function. It looks like this is not the case.

**Comment by helloworld415** [comment]
what should I do? please help me.  thank youu

**Comment by helloworld415** [comment]
do I need to configure something?

**Comment by hedii** [comment]
please search on google, i do not have time, sorry...

**Comment by helloworld415** [comment]
ok sir thank you. sorry for disturbing
