### ISSUE TITLE
user cant logged in

### ISSUE THREAD

**Issue by pranayuma92** [hedii/Codeigniter-Forum#9]
hi hedii, first  i wanna say thank you & good job for your work. i was downloaded & tried your codeigniter forum, everything works perfect when i try installation, login, register & logout. but when i logged in as admin & try accessing admin page, it redirect me back to home page. it same too when i logged in as normal user i cant edit profile, cant post, even i cant see edit button in my profile. can you please help me? thanks anyway & sorry for my bad english

**Comment by hedii** [comment]
it looks like you are having problem with sessions.

try to uncomment these lines to see the session content (username, logged_in, is_confirmed, is_admin, etc...): https://github.com/hedii/Codeigniter-Forum/blob/master/application/views/header.php#L56

**Comment by pranayuma92** [comment]
now everything works fine, thanks hedii
